#!/bin/bash

# The goal of this script is to retain the pretty nature of manifests, whilst updating
# the "releases:" section with a stemcell-restricted compiled release
#
# If we use `spruce merge` to do the job, the entire manifest will be reordered -
# keys will be sorted alphabetically. Comments will be lost.
#
# Instead, only the "releases:" block is replaced; the rest of the file
# is copied through as it is.
set -e

NAME=$1
VERSION=$2
RELEASE_TGZ_URL=$3
RELEASE_TGZ_SHA1=$4
STEMCELL_OS=$5
STEMCELL_VERSION=$6

if [[ "${STEMCELL_VERSION:-X}" == "X" ]]; then
  echo "USAGE: update-manifest-release NAME VERSION URL SHA1 STEMCELL_OS STEMCELL_VERSION"
  exit 1
fi
: ${REPO_ROOT:?required}
: ${REPO_OUT:?required}

# So, this is a nested bash/spruce/jq combo.
# What is happening here is that the "releases:" section of each deployment manifest
# is being updated with the new version/sha1 for the release.
#
# We use "spruce json manifest.yml | jq '.releases'" to extract the existing releases array
# and the '.releases | map(if .name == $name)' will modify a specific element of the array
#
# This gives us a modified "releases: [{...}, {...}]" segment of the final deployment manifest.
# We now need to merge this back into the original manifest.
#
# But, I don't want to just use `spruce merge` for this as it will reorder the manifest and
# make it ugly. If I didn't care about the manifest's aesthetics then this whole script
# would be simpler. I want the original layout of the manifest to be retained; and so
# we will just cut out the original "releases:" block and paste in the
# updated one where it was.
function bump_version {
  manifest_path=$1
  releases_updated=$(spruce merge <<YAML
releases: $(spruce json "$manifest_path" | jq --arg name $NAME --arg version $VERSION --arg url $RELEASE_TGZ_URL --arg sha1 $RELEASE_TGZ_SHA1 --arg stemcell_os $STEMCELL_OS --arg stemcell_version $STEMCELL_VERSION '.releases | map(
    if .name == $name
    then . + {"version":$version,"url":$url,"sha1":$sha1,"stemcell":{"os":$stemcell_os,"version":$stemcell_version}}
    else .
    end)'
)
YAML
)
  # The block ends at the next line that starts in column 0 and is not a
  # list item: the next key or a comment above it.
  RELEASES="$releases_updated" awk '
    /^releases:/     { print ENVIRON["RELEASES"]; skip = 1; next }
    skip && /^[^ -]/ { skip = 0; print "" }
    !skip
  ' "$manifest_path" > "$manifest_path.new"
  mv "$manifest_path.new" "$manifest_path"
}

for manifest_path in $(ls manifests/*.yml); do
  bump_version $manifest_path
done
